### ISSUE TITLE
Decoder zip not available

### ISSUE THREAD

**Issue by lilliangreenough** [StevenJohnsonOptics/Single-Pixel-Imaging#1]
I am getting error when trying to run the imageops.grayscale line, it says that "module 'PIL._imaging' has no attribute 'zip_decoder'". I have tried to google and I'm not really sure how to fix it, is it a problem with jupyterhub/ the version of python I'm using.

Thanks, 
Lillian

![Untitled](https://user-images.githubusercontent.com/72139022/94685003-b7a7db00-0320-11eb-8c47-fe0880a55602.jpg)

**Comment by StevenJohnsonOptics** [comment]
I have changed the code to use cv2 instead of PIL. I tried running the code in Jupyterlab and got the same error. I think installing Python might be easier in the long run. I use Anaconda, which comes with Jupyter (I perfer Spyder as it is easier to see variables). 
https://www.anaconda.com/products/individual
